### ISSUE TITLE
Typescript types

### ISSUE THREAD

**Issue by LukasKalbertodt** [polimediaupv/paella-core#1]
Hello there!

Since this is my first issue (of likely many), let me introduce myself: I'm currently the main dev on Tobira, the new video portal for Opencast. It is developed here: https://github.com/elan-ev/tobira. The development is currently funded by the ETH, which, as I understand it, also funds Paella 7. We want to use Paella 7 in Tobira and I started integrating it yesterday. 

We're happy to see that Paella is now usable via NPM and is more designed like a library. That already helps immensely! However, I already noticed a couple things that, in my opinion, are not optimal. We thought that you might be interested in this feedback. 

---

Now regarding the actual issue: in Tobira, we use Typescript (TS) as frontend language. TS is a superset of JavaScript that allows you to annotate types in several places, which are then used by the compiler to do type checking. If a library does not have types, it's harder for any TS project to use that library. Essentially, we need to write the types ourselves.

There are mainly three ways a library can provide types so that it can be nicely used from TS projects:

1. The library is itself written in Typescript. This is obviously not the case for Paella, so I guess this possibility is out. (Though, for the record, personally, I would recommend TS over JS for all projects)
2. The library is written in JS, but maintains types definitions (usually in `.d.ts` files) in its own repository.
3. The library is written in JS, but types are stored and maintained in [this huge official TS repository](https://github.com/DefinitelyTyped/DefinitelyTyped).

So what I'm basically asking is: how interested are you in TypeScript? If you are interested, it would be best to maintain the type definitions in this repository. But that only makes sense if you can actually maintain and adjust them when necessary. Otherwise, it would probably be better to let them live externally in the huge repo I linked. 

I'd be interested in providing type definitions for this library. I already partially did that, just to make it work in Tobira. The following is **very incomplete**, but just to give you an idea how these type definitions would look like:

<details>

```typescript
export class Paella {
    public constructor(node: string | HTMLElement, initParams: InitParams);

    public loadManifest(): Promise<void>;
}

export interface InitParams {
    configResourcesUrl?: string;
    configUrl?: string;
    repositoryUrl?: string;
    manifestFileName?: string;

    loadConfig?: (configUrl: string) => Promise<Config>;
    getVideoId?: () => Promise<string>;
    getManifestUrl?: (repoUrl: string, videoId: string) => Promise<string>;
    getManifestFileUrl?: (manifestUrl: string, manifestFileName: string) => Promise<string>;
    loadVideoManifest?: (manifestUrl: string) => Promise<Manifest>;

    customPluginContext?: unknown[];
}

export type Config = Record<string, unknown>;

// Definition: https://github.com/polimediaupv/paella-core/blob/main/doc/video_manifest.md
export interface Manifest {
    // https://github.com/polimediaupv/paella-core/blob/main/doc/video_manifest.md#metadata
    metadata: {
        duration: number;
        title?: string;
        preview?: string;
        // TODO: `related`
    };

    streams: {
        content: string;
        sources: {
            mp4?: Mp4Source[];
        };
        // TODO: `role`
    }[];

    // TODO: `frameList`
    // TODO: `captions`
}

// https://github.com/polimediaupv/paella-core/blob/main/doc/mp4-video-plugin.md
export interface Mp4Source {
    src: string;
    mimetype: "video/mp4";
    res: {
        w: number;
        h: number;
    };
}
```

</details>

Let me know what you think!

**Comment by ferserc1** [comment]
I know TS, and we considered using it, but we didn't do it for these reasons:

- If you need to use JS libraries without type definitions, it complicates the process a lot (as you well know).
- I would like to dispense with Babel in the future and let the browser interpret the JS code directly, at least in debugging, because I'm having a lot of problems with .map files for debugging. Using TS makes this option impossible.
- We are not using TS in any other project within our institution, so it would be a very complicated job to maintain and debug.
- The main reason: I am the only developer of Paella Player, and therefore I have very little time to maintain and debug it.

Considering all this, and given that Paella Player 7 is divided into several independent repositories, I think the only option is to maintain an independent type definition repository. Where to host or who is in charge of maintaining this repository is a question that is beyond my responsibilities, and perhaps it would be necessary to discuss it through another channel.

**Comment by LukasKalbertodt** [comment]
Ok, that's fair! Then I think we (Tobira) will maintain our own type definitions for Paella for now. Once those are somewhat usable and once Paella 7 is close to being released, we can think about releasing the type definitions somehow.
