### ISSUE TITLE
Consider adding a changelog with release notes for every released version

### ISSUE THREAD

**Issue by LukasKalbertodt** [polimediaupv/paella-core#107]
Hi there again! 
I just updated Paella to 1.3, but I've been wondering what changes were included in that release. I couldn't find any changelog here on github (neither releases nor as a file in the repository). The only thing I did find is https://paellaplayer.upv.es/#/doc/improvements.md, but this only lists minor releases, but not patch releases (e.g. `1.2.4`). 

It would be really helpful to have this information somewhere. I know very well that it's an annoying task eating up development time, but it really helps others. Also: it's possible to automate it completely (even if the release notes are not perfect then; it's still an improvement). GitHub has a pretty useful release note generator. One can also add a GitHub action that automatically publishes release notes whenever a tag is pushed (which you do).

If you're interested, I could prepare a PR with a GH action script that does exactly that: simply generate release notes for every pushed tag. Let me know!

**Comment by ferserc1** [comment]
According to paella-core's release rules, API changes are only added in minor versions. Patches are only used to fix bugs, and major versions are used to introduce changes that break the API of previous versions.

This document only contains changes to the API, so patches are not taken into account. The aim is to have a quick reference of the new features that are introduced, and in that sense, adding to the changelog the changes of all the resolved bugs would overcomplicate this file. It is possible that fixes to certain critical bugs may be added to improvements.md, but in any case whether this information is added or not cannot be decided automatically.

If you want, we can test how the solution you say goes, but in a separate file within the documentation.

**Comment by KatrinIhler** [comment]
As it stands, this policy makes it difficult to find out in which version a bug has been fixed. I just spent quite some time with a colleague to find a bug fix for captions not being available to select in Paella Player 7. We knew the version that was broken (1.39.3) and the version that worked (1.40.0) and found out through trial and error that the first version that worked was 1.39.7. We _assume_ it was fixed by this commit: https://github.com/polimediaupv/paella-core/commit/56d004968a8b2cb87ace2d8f3a7842d002fbb664 but the description doesn't really make this apparent, so it's just a guess.

So if you don't want to clutter up your documentation on API changes, a separate changelog containing all changes with helpful descriptions like `Fixed bug xy` would be very appreciated, as there aren't any pull requests to refer to and the commit messages are also pretty sparse.
