### ISSUE TITLE
Consider adding a test deployment of the latest Paella version

### ISSUE THREAD

**Issue by LukasKalbertodt** [polimediaupv/paella-core#109]
This could use github pages for example. I would imagine a test page where the player is shown, but that also has text input fields where one can change the manifest and configuration to test different settings. There should already be a default manifest and config with some test videos.

I see the following advantages:
- People like me, who use Paella in another application (e.g. Tobira), can see whether observed bugs are due to a configuration error or due to Paella itself. I don't want to waste your time by opening issues here that are not Paella's fault, but just me handing an invalid manifest to Paella.
- Bug reports can easily refer to the test deployment. It's a good reproducible example deployment. That's better than me always including links to Tobira's test deployment, where you don't know what other stuff Tobira configured, i.e. it's much harder for you to understand the whole picture.
- It's easier to test new Paella releases.

Just wanted to propose this idea here :)

**Comment by ferserc1** [comment]
What you are proposing already exists, and it is the website paellaplayer.upv.es. It is a Svelte application that is distributed with github pages, its repository is public and you can find it here:

https://github.com/polimediaupv/paellaplayer.upv.es

in the branch `paella-7-site`.

The problem is that there is nothing in the documentation where it is indicated, so I'm going to add it in the home page.

Translated with www.DeepL.com/Translator (free version)

**Comment by LukasKalbertodt** [comment]
Ah yeah ok. But that website doesn't seem to be automatically redeployed whenever there is a new Paella release, right? So it uses an old version of the player, right? And the player version is not indicated on the page, so the advantages I listed above don't really apply to this existing deployment.

But yeah, I'm obviously aware that this would cost time that might be better used in other areas. It's certainly a nice to have.

**Comment by ferserc1** [comment]
It is impossible to do this deploy automatically because the website depends also on the rest of the plugin libraries. Apart from that, many times doing this automatic deploy would be useless, because if new APIs are added, to test them I have to make changes in the code of the website.

Also keep in mind that this is the official website of the project, I can't make automatic releases without having previously tested that all the examples work well.

If I ever have the time, or if someone comes in to work on my team, there are many of these tasks that could be optimised, starting with integrating some testing framework.
