### ISSUE TITLE
Paella fails to load resource in Safari 16.1

### ISSUE THREAD

**Issue by guger** [polimediaupv/paella-core#147]
On macOS Ventura 13.0 and iPadOS 16.1 with Safari 16.1, Paella sticks in a loading loop and never starts playback of videos.

When using the developer console of Safari, the following error is shown:

`Failed to load resource: the server responded with a status of 404 (Not Found)`

from [https://.../paella/ui/resources/bootstrap/css/bootstrap.min.css.map](https://.../paella/ui/resources/bootstrap/css/bootstrap.min.css.map) and [https://.../paella/ui/hls.min.js.map](https://.../paella/ui/hls.min.js.map).

I'm not sure whether this is a Safari-Bug or a Paella bug, but it seems to be related to the browser engine, as it works on Safari 15.x.

If there's anything I can do to gather more information, please tell me!

**Comment by guger** [comment]
This bug does still occur in Safari 16.1 (18614.2.9.1.12) released with macOS 13.0.1 and iOS 16.1.1.

**Comment by nisaDoc** [comment]
I have also the same problem. Any ideas how to solve this?

**Comment by ferserc1** [comment]
We have not been able to reproduce the bug. Please note that in the case of video playback failures, it is important to include example links to facilitate debugging the problem.

If it is a m3u8 (hls) video, please refer to the documentation for common problems. These failures are usually related to the configuration of the HLS plugin (hls.js) or the encoding of the video.

- [HLS plugin](https://paellaplayer.upv.es/#/doc/hls_video_plugin.md)
- [HLS live and low latency HLS](https://paellaplayer.upv.es/#/doc/hls_live_video_plugin.md)

Note that the *.map files are used only for debugging, and are not usually deployed in production environments, that's why your browser can't find them. In any case, the lack of these files is not related to any bug.

**Comment by guger** [comment]
@ferserc1 I just tried the demos on https://paellaplayer.upv.es/#/demos and they work, so it really seems like this is an implementation problem. Thank you!

**Comment by renefs** [comment]
For those experiencing this issue, ensure that you are using the right plugin for your stream:

For non live streams:
```json
"sources": {
  "hls": [
     //...
  ]
}
```
For live streams
```json
"sources": {
  "hlsLive": [
    //...
   ]
}
```

With this configuration, it works for me
