### ISSUE TITLE
Paella 7 can fail is there is no default Image set

### ISSUE THREAD

**Issue by mliradelc** [polimediaupv/paella-core#190]
Hi,

We found this bug in Opencast*, but after research. I found that the code in paella core also is affected over this potential error.

*Live streaming is not load in Paella 7 because there is no default preview image.

What is the error,

If the media doesn't have `videoPreview`and `videoPreviewPortrait` and is not set in `config.json` a default value (`defaultVideoPreviewPortrait` and `defaultVideoPreview`) paella will fail to load the media.

The potential error is here:

https://github.com/polimediaupv/paella-core/blob/a3ef034d8ceb989dde79d1188d7da310a6931004/src/js/Paella.js#L96-L100

Suggested fixes:

1. Add a catch to continue with the player load even if the preview image are not available.
2. Add a function to generate a preview SVG file if there is manifest data (Title, author, etc).

I think the two suggestions can be implemented simultaneously. What are your thoughts?

**Comment by ferserc1** [comment]
As stated in the [documentation](https://paellaplayer.upv.es/#/doc/video_manifest.md), this is not a bug, it is the normal behaviour. It is mandatory to always have a preview image, because due to browser security settings, autoplay may not be available, even for live videos.

The first solution you propose is not feasible, because if the browser blocks autoplay, in some situations it can cause usability problems.

As for the second solution, I don't understand why you find this option better than simply defining a default image in the configuration, as the solution you propose also depends on having metadata available, whereas the default preview image always works.

If you are still interested in implementing the second option, you could do so without modifying paella-core, by overriding some of the [initialisation functions](https://paellaplayer.upv.es/#/doc/initialization.md) to provide a data URL in the `defaultVideoPreview` and `defaultVideoPreviewPortrait` fields. It is easy to generate an image from text using an HTML Canvas, from which you can get a data URL that you could place in these fields.
