### ISSUE TITLE
Disable logging completely via configuration

### ISSUE THREAD

**Issue by LukasKalbertodt** [polimediaupv/paella-core#2]
Paella uses `console.debug` a lot. While this is useful for debugging stuff, it becomes noisy quickly. So it would be very handy to be able to disable logging complete. It's fairly common for libraries to have a `debug` flag in their configurations. If that flag is set to `false`, nothing is ever printed via `console`. 

I'm not sure how much work it would be to change this, but it would certainly improve Paella as a library.

**Comment by ferserc1** [comment]
At the beginning of the version 7 project this was one of the issues that were taken into consideration.

The approach that has been followed in Paella Player 7 is to save as much code as possible in features that the browser offers natively, and initially we thought that using the verbosity flags of the debug console already provides a way to filter the console messages.

However, I am aware that using paella-core as part of a larger portal may cause inconvenience following this approach. To add a configurable log without modifying the prototypes of the `console` functions, it is necessary to create a log library (or use an existing one), and I had not considered it a priority because it was not a problem for the moment, but I will reconsider adding it to the API before releasing the final version.

**Comment by LukasKalbertodt** [comment]
> it is necessary to create a log library

Well, "a log library" sounds rather large. I guess the main issue could already solved by just defining a couple functions for logging in Paella. Those functions would just check a boolean `debug` flag, call `console.debug` if it is `true` or do nothing if it is `false`. And everywhere throughout Paella, one would use those new functions for logging. 

But I understand that this requires work/time that you cannot invest at the moment.

**Comment by LukasKalbertodt** [comment]
Oh, I'm sorry! I thought you closed the issue after writing your comment, but I now noticed that the issue was closed by a commit. That looks great! A configurable log level, sweet. Thanks!
