### ISSUE TITLE
Videos do not take advantage of all the available size

### ISSUE THREAD

**Issue by miesgre** [polimediaupv/paella-core#257]
Videos do not take advantage of all the available size.

Example from: https://paellaplayer.upv.es/player.html?id=portrait-dual

Example with videos taking advantage of the maximum possible size:
![Captura de pantalla 2023-06-05 a las 8 15 49](https://github.com/polimediaupv/paella-core/assets/2735202/9b246fc7-9b96-46c9-af6f-b21a9648776e)

if we make the window a bit smaller, the videos are repositioned leaving a lot of free space:
![Captura de pantalla 2023-06-05 a las 8 16 18](https://github.com/polimediaupv/paella-core/assets/2735202/e95d0d32-ca32-4df1-a56b-923f2a92e2b6)

**Comment by ferserc1** [comment]
Due to the huge number of possible combinations (N videos, each with different aspect ratios, portrait/landscape mixed) it is very difficult to find a compromise solution that works in all cases. Because of this, we must prioritiz the most common cases, and currently, in dual stream videos, the vast majority are in horizontal format.

This case occurs when both videos are in portrait format, and also the area available for viewing in the player window is higher than wide, even if only by a few pixels. Due to the problems that can cause the solution of this case, to the detriment of much more common cases, for the moment we are not going to give solution to this issue.
