### ISSUE TITLE
Tab/Keyboard control: The ESC key should allow the user to escape out of slides navigation

### ISSUE THREAD

**Issue by miesgre** [polimediaupv/paella-core#294]
The navigation slides have no way to escape by keyboard or voice control when open. The only way to escape is by using the mouse (or possibly to go through all of them, which is sometime a lot of slides).
The ESC key should allow the user to escape out of slides navigation.
@karendolan

**Comment by polimediaupv** [comment]
Timeline pop ups are designed so that they can remain open during the entire video playback, so it is possible to have a normal pop up and a timeline pop up open at the same time.

In addition, the pop ups have no focus, so it is not possible to determine which one has been activated first, and therefore another criterion has to be found to handle the ESC key press when there are timeline pop ups and normal pop ups open simultaneously.

To implement this function we will take into account the fact that the timeline pop ups are intended to remain open permanently, so the ESC key will close all the normal pop ups first, and when none of them are open the timeline pop up will be closed.

**Comment by ferserc1** [comment]
Fixed in version 1.43
