### ISSUE TITLE
Make `hideUiTime` configurable

### ISSUE THREAD

**Issue by LukasKalbertodt** [polimediaupv/paella-core#335]
Hi there!

During Tobira development we noticed that the timeout until the UI is hidden is quite long. Compare [this comment](https://github.com/elan-ev/tobira/pull/938#issuecomment-1725106418). By digging through the code I found out it's fixed at 5000ms:

https://github.com/polimediaupv/paella-core/blob/4f9a0a74853ff83f97993961c616507beceeff60/src/js/Paella.js#L690-L692

It would be great if this was configurable. I would also suggest reducing the default timeout a bit. YouTube uses 3s for example. (But only if your mouse is still inside the player area; if it leaves, the UI is hidden immediately. I opened a separate issue for that: https://github.com/polimediaupv/paella-core/issues/336)

**Comment by ferserc1** [comment]
This attribute is configurable using the Paella object API:

[https://paellaplayer.upv.es/#/doc/paella_object.md](https://paellaplayer.upv.es/#/doc/paella_object.md)

**`hideUiTime`** (read/write): Set or get the amount of seconds that must elapse without user interaction, while the video is playing, to hide the user interface.

However, I can add a parameter in the configuration to set the default value of this timer so that it can be modified using the configuration, and at the same time it does not break the API operation.

**Comment by LukasKalbertodt** [comment]
Ohh I missed that, thanks for the information! Will try shortly.
For Tobira it doesn't matter whether it's also configurable via configuration, but I can imagine some other people preferring that.
