### ISSUE TITLE
`unload()` does not clear error message

### ISSUE THREAD

**Issue by LukasKalbertodt** [polimediaupv/paella-core#92]
I noticed this problem in Tobira, a single page app. When I visit a video with invalid URL, the "error loading video" message appears as expected. But when I then click on another video, the message does not disappear. Clicking on another video causes: `unload()` to be called on the current Paella object, and then a new Paella object is created on the same DOM node.I guess `unload` just need to clear the error message and everything else from the tree as well.

![image](https://user-images.githubusercontent.com/7419664/180727996-17b8b2d3-1c37-4f64-a658-a9e27e3eb3b6.png)

**Comment by ferserc1** [comment]
That use case occurs on the official paella player website, and there are three examples of errors that are recovered in a SPA website:

[https://paellaplayer.upv.es/#/demos/manifest-not-found](https://paellaplayer.upv.es/#/demos/manifest-not-found)

Once loaded, try another video. Some of the video sources don't work, but that's because I have to spend some time reviewing the demos. You can try `Dual stream video` or `HLS Multi Audio`, those do work. 

The paella player site is SPA, but there is one case in which the entire web is reloaded: if you try to load another video during a transition between two states, it's impossible to "cancel" that transition, and the only way to load another manifest without wait until the transition is done is reloading the page. For example, if you try to load a video that takes a long time, such as `Triple Stream`, and before it finishes loading you try to load another one, in that case the page reloads completely, because otherwise you have to wait for the previous video to finish loading. 

You can check how it is implemented at paellaplayer.upv.es at github:

https://github.com/polimediaupv/paellaplayer.upv.es/tree/paella-7-site

It is implemented with Svelte. Check the `src/Player` and `src/Demos` components for the implementation, in case it helps. You can also refer to the paella player lifecycle documentation. If you find any inconsistency between the documentation and the behavior of the player, please let me know so I can fix it.

[https://paellaplayer.upv.es/#/doc/life_cycle.md](https://paellaplayer.upv.es/#/doc/life_cycle.md)

There is one case where an error may occur when clearing the error message: if the new video manifest does not have the `metadata.preview` field set, the error is not cleared properly. Note that this is NOT A BUG. The `metadata.preview` field is mandatory in paella core, so if it is not present the player behavior is unpredictable.

**Comment by LukasKalbertodt** [comment]
Oh, we did in fact not set `metadata.preview`, so that's likely the problem. I'd argue that a preview image should not be mandatory though. But that's a different topic.

We solved it in another way, by forcing React to not reuse the DOM node.
