### ISSUE TITLE
Paella increases JS bundle size by a lot (1MB)

### ISSUE THREAD

**Issue by LukasKalbertodt** [polimediaupv/paella-core#98]
Something is not quite right when Paella is bundled (via webpack in our case). We simply add these to our `package.json`:

```json
    "paella-basic-plugins": "^1.2.0",
    "paella-core": "^1.2.4",
    "paella-zoom-plugin": "^1.2.0",
```

And then use `npx webpack  --mode=production` to create the JS bundle. (Of course, you can always checkout [our sources](https://github.com/elan-ev/tobira/tree/master/frontend) for more details. Or just ask me.)

The resulting bundle is quite large, with Paella making up roughly half of the total size. This makes Paella by far the biggest library in our bundle.

![image](https://user-images.githubusercontent.com/7419664/182325524-5c576a85-af4e-458a-945e-2447c291c4f4.png)

I think it's also interesting that `pealla-core` is a separate thingy and not under `node_modules` like all other libraries.

So this seems clearly wrong. I'm really not sure what is happening here and I have no experience releasing an NPM library. But we would greatly appreciate if you could investigate this. I would guess that somehow an non-minified version of Paella is bundled. 

Again, I'm happy to help investigating this!

**Comment by ferserc1** [comment]
I think the only thing that could be removed are the dependencies to node_modules. I tried this a few months ago, and the result was that the player stopped working. I plan to investigate it further, but now is not the time (remember that the Paella Player "team" is just me).

All other elements cannot be removed. Note that the system that runs the plugins is quite complex, and on top of that the player has its own APIs for user interfaces. This has been done to make the player as self-sufficient as possible, so that it can work within any framework, but it obviously has an impact on the code size.

On the other hand, the HLS.js library is a central part of how the player works. Before the first release of paella-core I had considered separating the HLS support plugins and taking them out of the library, but it seemed absurd to do so, as HLS is widely used and in the end you would always end up having to include that plugin. There is a smaller version of hls.js, which is about half the weight, but it doesn't include some features that are necessary.

Finally, the player icons are loaded in SVG format embedded in the code. For this reason, there are libraries such as `paella-basic-plugins` that may seem heavy, but the reason is precisely because they include the icons.

Anyway, considering that we're talking about a multistream video player that is mainly used for teaching, do you really see such a problem with your bundle taking up 2MB? It's certainly something I want to look into, but it's far from my priorities.

**Comment by LukasKalbertodt** [comment]
> Anyway, considering that we're talking about a multistream video player that is mainly used for teaching, do you really see such a problem with your bundle taking up 2MB? It's certainly something I want to look into, but it's far from my priorities.

Totally understandable. 

And yes, videos being large anyway is a good reason why the bundle size doesn't really matter that much. However, for the argument to work, we assume that other application do code splitting and the Paella player is only loaded when the video is. If Paella is instead bundled in the one main of the application, it increases page load times before any video is loaded. But yeah, applications should do code splitting, so it's a fair point.

I opened this issue mainly because Tobira currently does not do code splitting (that's our fault, yes) and bc I am just confused by the huge bundle. I couldn't really understand why Paella would be that large. I already suspected it's just a build script bug where it would be bundled without optimizations or so. But ye ok, maybe Paella just contains a lot of code actually.

**Comment by LukasKalbertodt** [comment]
Oh, I just now tested a quick idea: the SVG icons (at least here in `paella-core`) could be shrunk a bit. I just used inkscape to export them as "optimized SVG". The two examples I tested with: `close.svg` (from 633 bytes to 291) and `minimize-3.svg` (from 1553 bytes to 957). Seems like that would be something like 7KB in total that the icons could be reduced in size. 

But again, I'm not saying Paella should really do that. This is just "for your information". This is certainly low priority, I agree.
